spring:
  application:
    name:
      gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      httpclient:
        ssl:
          use-insecure-trust-manager: true
        connect-timeout: 5000
        response-timeout: 10000
      routes:
        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/auth/**
        - id: publication-service
          uri: lb://profile-service
          predicates:
            - Path=/api/**
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/ws/**
          #filters:
          #  - StripPrefix=1
    consul:
      host: http://consul
      port: 8500
server:
  port: 8080

validateUrl:
  http://security-service:8765/auth/validate?token=