server:
  port: 45295

ENCRYPTION_KEY: ${ENCRYPTION_KEY}

PATH_TO_TEMPORARY_STORAGE: /files/temporary-storage
PATH_TO_COMPRESSED_STORAGE: /files/compressed-storage
PATH_TO_ENCRYPTED_STORAGE: /files/encrypted-storage
PATH_TO_PERMANENT_STORAGE: /files/permanent-storage

compression:
  text-type: text

  binary-type: application

spring:
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000, expireAfterWrite=10m

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB

  application:
    name: file-storage-service

  datasource:
    url: jdbc:postgresql://fileStorageDb:5432/fileStorageDb
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  cloud:
    consul:
      host: http://consul
      port: 8500