server:
  port: 45295

spring:
  application:
    name: file-storage-service

  datasource:
    url: jdbc:postgresql://fileStorageDb:5432/fileStorageDb
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  cloud:
    consul:
      host: http://consul
      port: 8500