server:
  port: 45295

PATH_TO_TEMPORARY_STORAGE: /files/temporary-storage
PATH_TO_COMPRESSED_STORAGE: /files/compressed-storage
PATH_TO_ENCRYPTED_STORAGE: /files/encrypted-storage
PATH_TO_PERMANENT_STORAGE: /files/permanent-storage

encryption:
  text-types: txt,log,md,csv,tsv,json,xml,yaml,yml,ini,conf,
              cfg,properties,env,html,htm,css,js,sh,bash,ps1,
              py,php,rb,java,kt,go,rs,c,cpp,h,hpp,rtf,odt,ods,
              tex,vcf,ics,sub,srt,svg

  binary-types: bmp,cr2,nef,arw,dng,tiff,psd,wav,aiff,pdf

  compressed-types: jpg,jpeg,png,gif,webp,zip,rar,7z,gz,tar,bz2,docx,xlsx,pptx,odp,odg,epub

spring:

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB

  application:
    name: file-storage-service

  datasource:
    url: jdbc:postgresql://fileStorageDb:5432/fileStorageDb
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  cloud:
    consul:
      host: http://consul
      port: 8500