server:
  port: 45295

spring:
  application:
    name: storage-service

  datasource:
    url: jdbc:postgresql://storageDb:5432/storageDb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  cloud:
    consul:
      host: http://consul
      port: 8500