server:
  port: 45295

ENCRYPTION_KEY: ${ENCRYPTION_KEY}

PATH_TO_TEMPORARY_STORAGE: /files/upload/temporary-storage
PATH_TO_COMPRESSED_STORAGE: /files/upload/compressed-storage
PATH_TO_ENCRYPTED_STORAGE: /files/upload/encrypted-storage
PATH_TO_PERMANENT_STORAGE: /files/upload/permanent-storage

PATH_TO_PREPARED_FOR_GET_STORAGE: /files/get/prepare-for-get-storage
PATH_TO_DECRYPTED_STORAGE: /files/get/decrypted-storage
PATH_TO_DECOMPRESSED_STORAGE: /files/get/decompressed-storage
PATH_TO_READY_FOR_GET_STORAGE: /files/get/ready-for-get-storage

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://jaeger:4317

opentelemetry:
  service-name: ${spring.application.name}

compression:
  text-type: text
  binary-type: application

spring:
  application:
    name: file-storage-service

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000, expireAfterWrite=10m

  servlet:
    multipart:
      enabled: true
      max-file-size: 300MB
      max-request-size: 315MB

  datasource:
    url: ${DBUrl}
    username: ${DBUsername}
    password: ${DBPassword}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  config:
    import: vault://

  cloud:
    consul:
      host: http://consul
      port: 8500